### ISSUE TITLE
RedisBungee should support Redis Sentinel

### ISSUE THREAD

**Issue by Cobi** [minecrafter/RedisBungee#17]
RedisBungee should support Redis Sentinel for redundant deployments of Redis.  I would prefer that the server running Redis not be a single point of failure.

**Comment by minecrafter** [comment]
Although I don't anticipate most RedisBungee users needing Sentinel, I will investigate adding support for it.

**Comment by minecrafter** [comment]
@Cobi: I don't think I will add Redis Sentinel support to the public version of RedisBungee just yet, mainly due to support and time constraints. How badly would you want this?

**Comment by Chnkr** [comment]
@Cobi and others looking for this feature, I'm planning to add support for Redis Sentinel if there are still people looking for it, so please do let me know :+1:

**Comment by detobel36** [comment]
News about that ?

**Comment by Chnkr** [comment]
There where no requests to add it in the past few months

**Comment by detobel36** [comment]
hum :confused:          
And if I would like to develop it myself, what needs to be changed ?  I thought it was natively supported by redis...

**Comment by Moehritz** [comment]
Honestly, the required changes are minimal.

I built Sentinel support into RedisBungee a while ago (this has not made it into a PR because the source of the JedisPool came from one of my personal plugins)

Basically, it's just replacing  `JedisPool` with `Pool<Jedis>` (which is a parent class). Tbh, that's everything it takes to make RedisBungee compatible with Sentinel. Now you just have to initialize it, which is euqally simple: 
Old: `new JedisPool(config, redisServer, redisPort, 0, finalRedisPassword);`
New: `new JedisSentinelPool(master, hosts, config, finalRedisPassword);`
